---
title: 'Cacho: Simulation Results'
author: "Nicolas Nunez-Sahr"
date: "2023-11-28"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)

bs_prob_data = read.csv(file = paste0(getwd(), '/game/simulation_results/cacho_29112023133240.csv'))
```

```{r winning_probs}
bs_prob_results = bs_prob_data %>%
  group_by(player_id, risk_thres) %>%
  summarise(win_probability = mean(win_bool), n = n())


ggplot(bs_prob_results, aes(x=risk_thres, y=win_probability)) +
  geom_point(aes(size=n)) +
  geom_line() +
  geom_hline(yintercept = 1/3, color = 'grey')


# simulation_results2 = sim_data2 %>%
#   mutate(rounded_bs_threshold = round(call_bullshit_threshold, 1)) %>% 
#   group_by(rounded_bs_threshold) %>%
#   summarise(win_probability = mean(win_bool), n = n())
# 
# 
# ggplot(simulation_results2, aes(x=rounded_bs_threshold, y=win_probability)) +
#   geom_point(aes(size=n)) +
#   geom_line() +
#   geom_hline(yintercept = 1/3, color = 'grey')

```


```{r simulate_beta}
library(geomtextpath)
library(latex2exp)

p = seq(0, 1, 0.01)
alpha = 10 * (1/3)
beta = 10 * (2/3)
mean = round(alpha / (alpha + beta), 2)
beta_density = dbeta(x = p, shape1 = alpha, shape2 = beta)
beta_df = data_frame(p=p, density=beta_density)
beta_prior = ggplot(beta_df, aes(x=p, y=density)) +
  geom_line() +
  theme_minimal() +
  geomtextpath::geom_textvline(xintercept = alpha / (alpha + beta), linetype = 2, label = paste0('Mean = ', mean), hjust = 0) +
  labs(title = unname(TeX('Prior: Beta Distribution with Parameters $\\alpha = 10 \\times \\frac{1}{3}, \\beta = 10 \\times (1 - \\frac{1}{3})$'))) +
  theme(plot.title = element_text(hjust = 0.5))
```



<!-- # $\alpha_{d, 0} =$ number of unseen dice $\times$ probability of d -->
<!-- # $\beta_{d, 0} =$ number of unseen dice $\times$ probability of not d -->

<!-- # $\alpha_{d, 1} = \alpha_{d, 0}$ + $I($d called on last turn$)$ -->
<!-- # $\beta_{d, 1} = \beta_{d, 0}$ + $I($d not called on last turn$)$  -->

<!-- # $\hat{p}_{3, 1} = \frac{\alpha_{d, 1}}{\alpha_{d, 1} + \beta_{d, 1}}$ -->


```{r beta_evol}
library(tidyr)
library(viridis)
p = seq(0, 1, 0.01)
alpha1 = 10 * (1/3)
beta1 = 10 * (2/3)

alpha2 = alpha1 + 1
beta2 = beta1

alpha3 = alpha2 + 1
beta3 = beta2

mean1 = round(alpha1 / (alpha1 + beta1), 5)
mean2 = round(alpha2 / (alpha2 + beta2), 5)
mean3 = round(alpha3 / (alpha3 + beta3), 5)
beta_density1 = dbeta(x = p, shape1 = alpha1, shape2 = beta1)
beta_density2 = dbeta(x = p, shape1 = alpha2, shape2 = beta2)
beta_density3 = dbeta(x = p, shape1 = alpha3, shape2 = beta3)
beta_df = data_frame(p=p, 'Turn 1'=beta_density1, 'Turn 2'=beta_density2, 'Turn 3'=beta_density3)
beta_df_g = beta_df %>% 
  gather('Turn', 'Density', 'Turn 1', 'Turn 2', 'Turn 3')

(beta_evol = ggplot(beta_df_g, aes(x=p, y=Density, group = Turn, color = Turn)) +
  geomtextpath::geom_textline(label = beta_df_g$Turn, hjust=0.2) +
  geomtextpath::geom_textvline(xintercept = mean1, color = palette()[3], label = paste0('Probability Turn 1 = ', mean1), hjust=0.1) +
  geomtextpath::geom_textvline(xintercept = mean2, color = palette()[4], label = paste0('Probability Turn 2 = ', mean2), hjust=0.1) +
  geomtextpath::geom_textvline(xintercept = mean3, color = palette()[5], label = paste0('Probability Turn 3 = ', mean3), hjust=0.1) +
  scale_color_manual(guide='none', values = palette()[3:5]) +
  theme_minimal() +
    ggtitle('Estimate of Binomial Parameter p of Dice = 3 by Turn') +
    theme(plot.title = element_text(hjust = 0.5)))

num_unseen_dice = 10
q = seq(0, 10, 1)
binomial_cdf_probs1 = c(1, 1, 1, 1 - pbinom(q=q, prob = mean1, size = num_unseen_dice), 0, 0)
binomial_cdf_probs2 = c(1, 1, 1, 1 - pbinom(q=q, prob = mean2, size = num_unseen_dice), 0, 0)
binomial_cdf_probs3 = c(1, 1, 1, 1 - pbinom(q=q, prob = mean3, size = num_unseen_dice), 0, 0)
q = c(0, 1, 2, q + 3, 14, 15)

binomials_df = data.frame(x = q, 'Turn 1' = binomial_cdf_probs1, 'Turn 2' = binomial_cdf_probs2, 'Turn 3' = binomial_cdf_probs3)
colnames(binomials_df) = c('x', 'Turn 1', 'Turn 2', 'Turn 3')
binomials_df_g = binomials_df %>% 
  gather('Turn', 'Probability', 'Turn 1', 'Turn 2', 'Turn 3')

(binomial_evol = ggplot(binomials_df_g, aes(x=x, y=Probability, group = Turn, color = Turn)) +
  geomtextpath::geom_textline(label = binomials_df_g$Turn, hjust=0.3) +
  geomtextpath::geom_textvline(xintercept = 3 + mean1*(num_unseen_dice), color = palette()[3], label = paste0('Mean: ', 3 + mean1*(num_unseen_dice)), hjust=0.9) +
  geomtextpath::geom_textvline(xintercept = 3 + mean2*(num_unseen_dice), color = palette()[4], label = paste0('Mean: ', 3 + mean2*(num_unseen_dice)), hjust=0.9) +
  geomtextpath::geom_textvline(xintercept = 3 + mean3*(num_unseen_dice), color = palette()[5], label = paste0('Mean: ', 3 + mean3*(num_unseen_dice)), hjust=0.9) +
  scale_color_manual(guide='none', values = palette()[3:5]) +
  theme_minimal() +
    ggtitle('Conditional At Least Distribution of Count of 3\'s') +
    scale_x_continuous(name = 'Count of 3\'s', breaks = seq(0, 15)) +
    theme(plot.title = element_text(hjust = 0.5)) +
    geomtextpath::geom_texthline(yintercept = 0.37, label = 'Bullshit Tolerance', hjust=0.05))
```


```{r beta_other_evol}
library(tidyr)
library(viridis)
p = seq(0, 1, 0.01)
alpha1 = 10 * (1/3)
beta1 = 10 * (2/3)

alpha2 = alpha1
beta2 = beta1 + 1

alpha3 = alpha2
beta3 = beta2 + 1

mean1 = round(alpha1 / (alpha1 + beta1), 5)
mean2 = round(alpha2 / (alpha2 + beta2), 5)
mean3 = round(alpha3 / (alpha3 + beta3), 5)
beta_density1 = dbeta(x = p, shape1 = alpha1, shape2 = beta1)
beta_density2 = dbeta(x = p, shape1 = alpha2, shape2 = beta2)
beta_density3 = dbeta(x = p, shape1 = alpha3, shape2 = beta3)
beta_df = data_frame(p=p, 'Turn 1'=beta_density1, 'Turn 2'=beta_density2, 'Turn 3'=beta_density3)
beta_df_g = beta_df %>% 
  gather('Turn', 'Density', 'Turn 1', 'Turn 2', 'Turn 3')

(beta_evol = ggplot(beta_df_g, aes(x=p, y=Density, group = Turn, color = Turn)) +
  geomtextpath::geom_textline(label = beta_df_g$Turn, hjust=0.2) +
  geomtextpath::geom_textvline(xintercept = mean1, color = palette()[3], label = paste0('Probability Turn 1 = ', mean1), hjust=0.1) +
  geomtextpath::geom_textvline(xintercept = mean2, color = palette()[4], label = paste0('Probability Turn 2 = ', mean2), hjust=0.1) +
  geomtextpath::geom_textvline(xintercept = mean3, color = palette()[5], label = paste0('Probability Turn 3 = ', mean3), hjust=0.1) +
  scale_color_manual(guide='none', values = palette()[3:5]) +
  theme_minimal() +
    ggtitle('Estimate of Binomial Parameter p of Dice != 3 by Turn') +
    theme(plot.title = element_text(hjust = 0.5)))

num_unseen_dice = 10
q = seq(0, 10, 1)
binomial_cdf_probs1 = c(1, 1, 1, 1 - pbinom(q=q, prob = mean1, size = num_unseen_dice), 0, 0)
binomial_cdf_probs2 = c(1, 1, 1, 1 - pbinom(q=q, prob = mean2, size = num_unseen_dice), 0, 0)
binomial_cdf_probs3 = c(1, 1, 1, 1 - pbinom(q=q, prob = mean3, size = num_unseen_dice), 0, 0)
q = c(0, 1, 2, q + 3, 14, 15)

binomials_df = data.frame(x = q, 'Turn 1' = binomial_cdf_probs1, 'Turn 2' = binomial_cdf_probs2, 'Turn 3' = binomial_cdf_probs3)
colnames(binomials_df) = c('x', 'Turn 1', 'Turn 2', 'Turn 3')
binomials_df_g = binomials_df %>% 
  gather('Turn', 'Probability', 'Turn 1', 'Turn 2', 'Turn 3')

(binomial_evol = ggplot(binomials_df_g, aes(x=x, y=Probability, group = Turn, color = Turn)) +
  geomtextpath::geom_textline(label = binomials_df_g$Turn, hjust=0.3) +
  geomtextpath::geom_textvline(xintercept = 2 + mean1*(num_unseen_dice), color = palette()[3], label = paste0('Mean: ', 2 + mean1*(num_unseen_dice)), hjust=0.1) +
  geomtextpath::geom_textvline(xintercept = 2 + mean2*(num_unseen_dice), color = palette()[4], label = paste0('Mean: ', 2 + mean2*(num_unseen_dice)), hjust=0.1) +
  geomtextpath::geom_textvline(xintercept = 2 + mean3*(num_unseen_dice), color = palette()[5], label = paste0('Mean: ', 2 + mean3*(num_unseen_dice)), hjust=0.1) +
  scale_color_manual(guide='none', values = palette()[3:5]) +
  theme_minimal() +
    ggtitle('Conditional At Least Distribution of Count of 5\'s') +
    scale_x_continuous(name = 'Count of 5\'s', breaks = seq(0, 15)) +
    theme(plot.title = element_text(hjust = 0.5)) +
    geomtextpath::geom_texthline(yintercept = 0.37, label = 'Bullshit Tolerance', hjust=0.05))
```


# trustability
```{r trust}
# trust_data = read.csv(file = paste0(getwd(), '/game/simulation_results/trust_29112023004446.csv'))
# 
# trust_results = trust_data %>%
#   mutate(rounded_trust = round(trustability, 1)) %>% 
#   group_by(rounded_trust) %>%
#   summarise(win_probability = mean(win_bool), n = n())
# 
# 
# ggplot(trust_results, aes(x=rounded_trust, y=win_probability)) +
#   geom_point(aes(size=n)) +
#   geom_line() +
#   geom_hline(yintercept = 1/3, color = 'grey')
```
